apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/laravel
- ../../base/mysql
- ../../base/jobs

# Development environment uses .env file for secrets
secretGenerator:
- files:
  - ../../base/secrets/.env
  name: laravel-secrets
  type: Opaque
generatorOptions:
  disableNameSuffixHash: true

patches:
- path: patch-laravel-replicas.yaml
- path: patch-laravel-pvc.yaml
