apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/laravel
- ../../base/mysql
- ../../base/jobs

# Development environment uses .env file for secrets
secretGenerator:
  - name: laravel-secrets
    files:
      - ../../base/secrets/.env
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- patch-laravel-replicas.yaml
