apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/laravel
- ../../base/mysql
- ../../base/jobs

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patch-laravel-replicas.yaml
