apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedeagle/laravel-gitops-k8s.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: # Automatically sync the application with the Git repository.
      prune: true # Automatically delete resources that are no longer defined in Git.
      selfHeal: true # Automatically revert changes made directly in the cluster.
    syncOptions:
      - CreateNamespace=true # Automatically create the namespace if it does not exist.