apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/laravel
- ../../base/mysql
- ../../base/jobs
- ../../base/secrets

patches:
- path: patch-laravel-replicas.yaml
- path: patch-laravel-pvc.yaml
