apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/laravel
  - ../../base/mysql
  - ../../base/jobs
  - ../../base/secrets # Using existing sealed secrets

patchesStrategicMerge:
  - patch-laravel-replicas.yaml
