apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: default
type: Opaque
stringData:
  # Laravel Application Secrets
  APP_NAME: Laravel
  APP_ENV: local
  APP_KEY: base64:YhTxsZD2UdfAnfFy6wH+x8ZZW8JbtaWBiMje7eqmnNo=
  APP_DEBUG: "true"
  APP_URL: http://localhost

  # Database Configuration
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root

  # MySQL Configuration
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: laravel

  # Redis Configuration (if needed)
  REDIS_HOST: redis
  REDIS_PASSWORD: null
  REDIS_PORT: "6379"

  # Mail Configuration (if needed)
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: null
  MAIL_FROM_NAME: "${APP_NAME}"

  # AWS Configuration (if needed)
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  # Session and Cache
  SESSION_DRIVER: file
  CACHE_DRIVER: file 

  #kubeseal --format yaml --cert=../../pub-cert.pem < laravel-secret.yaml > laravel-secret-sealed.yaml
