resources:
- laravel/
- mysql/
- jobs/
- secrets/
- pvc-laravel-storage.yaml
# This file is a Kustomization file for Kubernetes, which allows you to manage and customize Kubernetes resources.


# Add labels to all resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: argocd
