apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      imagePullSecrets:
        - name: ecr-secret
      volumes:
        - name: nginx-config
          configMap:
            name: laravel-nginx-config
      containers:
        - name: php-fpm
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql
          envFrom:
            - secretRef:
                name: laravel-secrets
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
        - name: migrate
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
          command: ["sh", "-c", "if [ ! -f /var/www/storage/.migrated ]; then php artisan migrate --force && touch /var/www/storage/.migrated; fi"]
          env:
            - name: DB_HOST
              value: mysql
          envFrom:
            - secretRef:
                name: laravel-secrets
