apiVersion: batch/v1
kind: CronJob
metadata:
  name: laravel-scheduler
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduler
              image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
              command: ["php", "artisan", "schedule:run"]
              envFrom:
                - secretRef:
                    name: laravel-secrets
          restartPolicy: OnFailure
