apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_DATABASE: laravel
  APP_KEY: base64:YhTxsZD2UdfAnfFy6wH+x8ZZW8JbtaWBiMje7eqmnNo=
