apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      imagePullSecrets:
        - name: ecr-secret
      restartPolicy: Never
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until mysqladmin ping -h mysql -uroot -proot --silent; do echo "Waiting for MySQL login..."; sleep 5; done']
      containers:
        - name: migrate
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - secretRef:
                name: laravel-secrets
