apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 1
  template:
    spec:
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 mysql 3306; do echo "Waiting for MySQL..."; sleep 5; done']  
      containers:
        - name: migrate
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - secretRef:
                name: laravel-secrets
      restartPolicy: Never
  # Ensure the job runs after the MySQL deployment is ready
