apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: wait-for-mysql
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL to be ready...";
              until mysqladmin ping -h mysql -uroot -proot --silent; do
                echo "Still waiting...";
                sleep 5;
              done
      containers:
        - name: migrate
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - secretRef:
                name: laravel-secrets