apiVersion: v1
kind: PersistentVolumeClaim #a Kubernetes object that requests disk storage from your cluster.
metadata:
  name: laravel-storage-pvc
spec:
  storageClassName: standard        # Use default
  accessModes:
    - ReadWriteOnce # This means the volume can be mounted as read-write by a single node.
  # Uncomment the following line if you want to use AWS EFS
 # storageClassName: efs-sc  AWS EFS volume already created #EFS CSI driver installed in your cluster #A StorageClass YAML like this:
  resources:
    requests:
      storage: 1Gi # Default size (overridden in overlays)
