# ---------------------------
# ✅ Laravel Migration Job (ArgoCD Hook)
# ---------------------------
# File: migrate-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo "Waiting for MySQL..."; sleep 5; done']
        - name: fix-storage-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/www/storage"]
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-storage-pvc
      containers:
        - name: migrate
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
          command: ["sh", "-c", "sleep 5 && php artisan migrate --force"]
          env:
            - name: DB_HOST
              value: mysql
          envFrom:
            - secretRef:
                name: laravel-secrets
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
