apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-queue-worker
  labels:
    app: laravel
    component: queue-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
      component: queue-worker
  template:
    metadata:
      labels:
        app: laravel
        component: queue-worker
    spec:
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo "Waiting for MySQL..."; sleep 5; done']
        - name: fix-storage-permissions
          image: busybox
          command: ["sh", "-c", "chown -R www-data:www-data /var/www/storage"]
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-storage-pvc
      containers:
        - name: queue-worker
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-worker:latest
          command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
          env:
            - name: DB_HOST
              value: mysql
            - name: SUPERVISOR_PROCESS_NAME
              value: "laravel-worker"
            - name: QUEUE_CONNECTION
              value: "redis"
            - name: REDIS_HOST
              value: "redis"
          envFrom:
            - secretRef:
                name: laravel-secrets
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command: ["supervisorctl", "status"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["supervisorctl", "status"]
            initialDelaySeconds: 5
            periodSeconds: 5
