apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisor-config
data:
  supervisord.conf: |
    [unix_http_server]
    file=/var/run/supervisor.sock
    chmod=0700

    [supervisord]
    logfile=/var/log/supervisor/supervisord.log
    pidfile=/var/run/supervisord.pid
    childlogdir=/var/log/supervisor

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

    [supervisorctl]
    serverurl=unix:///var/run/supervisor.sock

    [include]
    files = /etc/supervisor/conf.d/*.conf

  laravel-worker.conf: |
    [program:laravel-worker]
    process_name=%(program_name)s_%(process_num)02d
    command=php /var/www/artisan queue:work --tries=3 --timeout=90
    autostart=true
    autorestart=true
    user=www-data
    numprocs=4
    redirect_stderr=true
    stdout_logfile=/var/log/supervisor/worker.log
    stopwaitsecs=3600
    startretries=3
    startsecs=10 