apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: fix-storage-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/www/storage"]
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
      volumes: #This part is declaring the available volumes for the whole pod (not container-specific):
        - name: nginx-config
          configMap: #this will load the nginx configuration from a ConfigMap file
            name: laravel-nginx-config
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-storage-pvc #"Please connect this volume to the storage defined by the PVC named laravel-storage-pvc
      containers:
        - name: php-fpm
          image: 043309367638.dkr.ecr.us-east-1.amazonaws.com/laravel-k8s:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql
          envFrom:
            - secretRef:
                name: laravel-secrets
          volumeMounts: # where to mount laravel-storage inside the container:
            - name: laravel-storage
              mountPath: /var/www/storage
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
